const Strings = {
  title: "Profile",
  personHeader: "Personal Information",
  avatar: "Avatar",
  changeBtn: "Change",
  removeBtn: "Remove",
  firstName: "First name",
  lastName: "Last name",
  email: "Email",
  phone: "Phone number",
  emailNoti: "Email notifications",
  orderStatuses: "Order statuses",
  passChanges: "Password changes",
  specialOffers: "Special offers",
  newsletters: "Newsletters",
  logout: "Logout",
  discardBtn: "Discard changes",
  saveChange: "Save changes",
  firstNameInvalid: "First name is invalid",
  lastNameInvalid: "Last name is invalid",
  emailInvalid: "Email is invalid",
  phonelInvalid: "Phone is invalid",
  cancel: "Cancel",
  ok: "OK",
  logoutTitle: "Are you want to logout?",
  logoutMessage: "When user logout, all data will be removed from the device.",
};
export default Strings;
